### ISSUE TITLE
'skipRendering' has already been declared

### ISSUE THREAD

**Issue by DonutzAndCoffee** [hakanuzunoglu/TWF-Dash#4]
First of all: Thanks a lot for this brilliant Dash! Thumbs up! :) 

In the latest version 2.2.6 I see this error message:
TWF 2.2.6 throws this error message:
[2023-05-13 07:41:51,309] ERROR - Dashtemplates\TWF DASH\TWF DASH.djson, HELP, OverlayTriggerExpression : Expression (JS) const helpers = readtextfile('./JavascriptExtensions/TWF_DASH_HELPER.js')

if (helpers) {
    return 0 
} else {
    return 1
} has generated an error (Jint.Runtime.JavaScriptException: Identifier 'skipRendering' has already been declared ---> Jint.Runtime.JavaScriptException+JavaScriptErrorWrapperException: Identifier 'skipRendering' has already been declared
   --- End of inner exception stack trace ---
   at Jint.Runtime.ExceptionHelper.ThrowSyntaxError(Realm realm, String message)
   at Jint.Engine.GlobalDeclarationInstantiation(Script script, GlobalEnvironmentRecord env)
   at Jint.Engine.ScriptEvaluation(ScriptRecord scriptRecord)
   at Jint.Engine.<>cDisplayClass78_0.<Execute>b0()
   at Jint.Engine.ExecuteWithConstraints[T](Boolean strict, Func`1 callback)
   at Jint.Engine.Execute(Script script)
   at Jint.Engine.Execute(String code, String source, ParserOptions parserOptions)
   at Jint.Engine.Execute(String code, String source)
   at SimHubWPF.JintEngine.Execute(String v)
   at SimHub.Plugins.OutputPlugins.Dash.TemplatingCommon.NCalcEngineBase.LoadJavascriptExpression(ExpressionValue value)

Simhub Version is up to date: 8.3.10 and  TWF_DASH_HELPER.js and TWF_DASH_CONFIG.json are available in SimHub\JavascriptExtensions folder.

Any clue what is wrong?

**Comment by hakanuzunoglu** [comment]
Never witnessed this issue. Will check and confirm tomorrow.

**Comment by hakanuzunoglu** [comment]
I am not able to replicate the problem. Is the dash working fine for you? I mean is it still working while generating this error?

**Comment by DonutzAndCoffee** [comment]
Hi!The issue is solved already. It was related to other js files laying around in the extensions folder. I simply cleaned up / deleted unused files. Wotever mentioned he updated the JS library.  It is more strict now in some error handling areas. Best regardsOliverAm 14.05.2023 um 05:04 schrieb hakanuzunoglu ***@***.***>:﻿
I am not able to replicate the problem. Is the dash working fine for you? I mean is it still working while generating this error?

**Comment by hakanuzunoglu** [comment]
Thank you. Good to know that the issue is resolved.
